### PR TITLE
fix: indexOf null while trying to read file without a name (frame source)

### LINKED ISSUE #121: [Javascript] Bug: Cannot read property `indexOf` of null
telegram-cloud-photo-size-2-5429450506461359845-y

### PR DESCRIPTION
**Pull request by talyguryn**
Do not try to get file lines (5 below/above the error string) if frame `source` is empty

resolve #121

### CODE REVIEW

**Review by ilyamore88 — APPROVED** [review]

File: workers/javascript/src/index.ts [hunk 1]
```diff
@@ -191,9 +193,15 @@ export default class JavascriptEventWorker extends EventWorker {
 
     /**
      * Source code lines
-     * 5 above and 5 below
      */
-    const lines = this.readSourceLines(consumer, originalLocation);
+    let lines = [];
+
+    if (originalLocation.source) {
```
Comment (neSpecc) [inline workers/javascript/src/index.ts:199]: опиши и прилинкуй issue в комментах плз

**Review by neSpecc — APPROVED** [review]
